services:
  rustpta:
    build: .
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - rustup-home:/usr/local/rustup
    tty: true

volumes:
  cargo-registry:
  cargo-git:
  rustup-home:
